disabled_rules:
  - file_length
  - force_cast
  - force_try
  - function_body_length
  - type_body_length

opt_in_rules:
  - attributes
  - closure_end_indentation
  - closure_spacing
  - conditional_returns_on_newline
  - empty_count
  - explicit_init
  - fatal_error_message
  - first_where
  - implicitly_unwrapped_optional
  - overridden_super_call
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - switch_case_on_newline

excluded:
  - Carthage
  - External

trailing_comma:
  mandatory_comma: true

trailing_whitespace:
  ignores_comments: false
  ignores_empty_lines: false
