#!/bin/bash -e

#
# clean_externals
#
# Removes the outputs from the various static library targets.
# Necessary when switching platforms/architectures as Xcode does not clean
# these for you.
#

# A list of external static libraries included in the SwiftGit2 framework
libraries=(
    External/libgit2.a
    External/libgit2-ios/libgit2-ios.a
    External/libssh2-ios/lib/libssh2-ios.a
    External/openssl/lib/libssl.a
    External/openssl/lib/libcrypto.a
    External/openssl/include/openssl
)

rm -vrf "${libraries[@]}"
